token: YOU_MUST_PUT_YOUR_TOKEN_HERE
owner_is_admin: true
use_logging_file: true
working_directory: null
admins: []
resources: null
logs:
  path: ./logs
  level: INFO
database: sqlite+aiosqlite://%(data)s/easterobot.db
group: egg
hunt:
  timeout: 300.0
  game: 0.75
  cooldown:
    min: 600.0
    max: 1800.0
  weights:
    base: 0.3
    egg: 0.4
    speed: 0.3
commands:
  search:
    cooldown: 600.0
    discovered:
      shield: 5
      min: 0.5
      max: 0.8
    spotted:
      shield: 10
      min: 0.4
      max: 0.7
  top:
    cooldown: 10.0
  connect4:
    cooldown: 120.0
  rockpaperscissor:
    cooldown: 120.0
  tictactoe:
    cooldown: 120.0
  basket:
    cooldown: 10.0
  reset:
    cooldown: 120.0
  enable:
    cooldown: 10.0
  disable:
    cooldown: 10.0
  help:
    cooldown: 10.0
  edit:
    cooldown: 30.0
conjugation:
  e:
    woman: "e"
  iel:
    man: "il"
    woman: "elle"
  le:
    man: "le"
    woman: "la"
  lui:
    man: "lui"
    woman: "elle"
failed:
  - "Malheureusement, tu n'as pas r√©ussi √† trouver d'≈ìufs cette fois-ci. Tu auras plus de chance la prochaine fois !"
  - "Tu n'as pas eu de chance cette fois-ci, mais ne te d√©courage pas ! Continue de chercher des ≈ìufs."
  - "Dommage, tu n'as pas trouv√© d'≈ìufs, mais ne t'inqui√®te pas, il y en aura en s√ªrement plus loin."
  - "Tu as cherch√© partout, mais malheureusement, tu n'as pas trouv√© d'≈ìufs. Essaie plus tard !"
  - "Tu n'as pas r√©ussi √† trouver d'≈ìufs. Continue de chercher, peut-√™tre que la prochaine fois sera la bonne !"
  - "Tu n'as pas eu de chance cette fois-ci, mais garde espoir ! Les ≈ìufs peuvent √™tre difficiles √† trouver, mais c'est ce qui rend le jeu int√©ressant."
  - "Il semble que tu n'aies pas r√©ussi √† trouver d'≈ìufs, mais ne te d√©courage pas. Essaie de nouvelles strat√©gies et continue de chercher !"
  - "Tu as cherch√© partout, mais malheureusement, tu n'as pas r√©ussi √† trouver d'≈ìufs cette fois-ci. Ne baisse pas les bras !"
  - "Tu n'as pas trouv√© d'≈ìufs. Mais ne t'inqui√®te pas, il y aura de nouvelles occasions de jouer et de trouver des ≈ìufs dans le futur."
  - "Tu n'as pas eu de chance cette fois-ci, mais rappelle-toi que l'important est de s'amuser en cherchant les ≈ìufs. Continue de jouer et tu finiras par trouver des ≈ìufs !"
  - "Eh bien, √ßa y est, tu as fouill√© tous les recoins et malheureusement, il n'y a pas d'≈ìufs √† l'horizon. Il semblerait que tu sois plus malchanceux qu'un chat noir."
  - "Tu as explor√© tous les recoins et les fissures, mais il n'y a pas d'≈ìufs √† trouver. C'est comme si tu cherchais une aiguille dans une botte de foin."
  - "H√©las, tu n'as pas r√©ussi √† d√©nicher d'≈ìufs. Mais garde le moral, tu es aussi tenace que Rocky Balboa."
  - "Malheureusement, tu n'as rien trouv√©. C'est comme si tu cherchais une licorne dans un champ de p√¢querettes."
  - "Tu as cherch√© partout, mais il n'y a pas d'≈ìufs √† l'horizon. Tu dois √™tre plus malchanceux que le personnage principal dans un film d'horreur."
  - "Tu as cherch√© avec acharnement, mais il n'y a pas d'≈ìufs, tu n'es pas dans Harry Potter o√π la baguette magique r√©sout tout."
  - "Il semblerait que tu aies manqu√© les ≈ìufs cette ann√©e, mais ne t'en fais pas, tu peux toujours essayer de trouver la fontaine de Jouvence comme Jack Sparrow."
  - "Tu as cherch√© avec acharnement, mais il n'y a pas d'≈ìufs ici, ils ont probablement √©t√© d√©vor√©s par les dragons de P√¢ques affam√©s."
  - "Malheureusement, tu n'as trouv√© aucun ≈ìuf, mais ne sois pas triste, tu as quand m√™me r√©ussi √† √©viter les lapins mal√©fiques de P√¢ques."
  - "D√©sol√©, tu as beau chercher, il n'y a pas d'≈ìufs ici, tu n'es pas dans un film de Willy Wonka."
  - "Tu cherches des ≈ìufs ici ? Mauvaise pioche, il n'y en a pas, juste toi et moi."
  - "Pas d'≈ìufs ici, mais si tu trouves un tr√®fle √† quatre feuilles, je te fais une r√©compense surprise."
  - "Tu cherches des ≈ìufs ? Pas de chance, je crois que le lapin les a tous gard√©s pour lui cette ann√©e."
  - "Je ne veux pas te casser le moral, mais il n'y a pas d'≈ìufs ici, juste des pixels vides et de la tristesse."
hidden:
  - "Bravo, aventurier! Tu as trouv√© un ≈ìuf perdu depuis des si√®cles. Il √©tait temps de le remettre √† sa place dans le panier !"
  - "F√©licitations, tu as battu les lapins de P√¢ques √† leur propre jeu en trouvant un ≈ìuf perdu. Pas mal pour un humain !"
  - "Ah, tu as trouv√© un ≈ìuf ! C'est une bonne chose que les lapins de P√¢ques ne t'ais pas attrap√© avant que tu ne le trouves !"
  - "Tu as d√©couvert un ≈ìuf ! Tu devrais peut-√™tre envisager de t'inscrire aux Jeux Olympiques de la Chasse aux ≈ìufs !"
  - "Tu es un vrai Sherlock Holmes des ≈ìufs de P√¢ques ! Maintenant, si seulement tu pouvais r√©soudre le myst√®re de qui a mang√© tous les chocolats de P√¢ques..."
  - "G√©nial ! Tu as trouv√© un ≈ìuf cach√©. Il est maintenant temps de te faire une omelette g√©ante au chocolat pour c√©l√©brer ta victoire !"
  - "F√©licitations ! Tu as mis la main sur un ≈ìuf, tu es un h√©ros ! Maintenant, tu as le droit de t'en vanter aupr√®s de tous tes amis."
  - "Bien jou√©, tu as r√©ussi √† trouver un ≈ìuf ! C'est l'≈ìuf le plus chanceux du monde car il a √©t√© trouv√© par toi !"
  - "Oh l√† l√†, regarde qui est un chasseur d'≈ìufs professionnel maintenant ! Bon boulot, mon ami !"
  - "Quelqu'un a appel√© les chasseurs de tr√©sors ? Tu viens de trouver un ≈ìuf, f√©licitations !"
  - "J'esp√®re que tu as un beau panier pour ranger ton nouvel ≈ìuf - c'est vraiment la perle rare !"
  - "Bravo ! Tu as remport√© la chasse aux ≈ìufs ! Maintenant, pr√©pare-toi √† gagner une autre comp√©tition contre tes confr√®res..."
  - "Le lapin de P√¢ques serait fier de toi ! Tu as trouv√© un ≈ìuf comme un pro."
  - "Les cloches de P√¢ques ont sonn√©, et tu as r√©pondu √† l'appel ! F√©licitations pour ta nouvelle trouvaille !"
  - "Tu viens de battre le record de la chasse aux ≈ìufs la plus rapide ! Tu as gagn√© un ≈ìuf en chocolat - et l'admiration √©ternelle."
  - "Qui a besoin d'un d√©tecteur de m√©taux quand on t'a ? Tu as trouv√© un ≈ìuf comme un vrai chasseur de tr√©sors !"
  - "Incroyable! Tu viens de gagner le grand prix de la chasse aux ≈ìufs - un grand sourire sur ton visage et une r√©serve infinie de bonheur sucr√©."
  - "Alors, comment se sent-on d'√™tre le ma√Ætre de la chasse aux ≈ìufs ? Tu vas pouvoir le c√©l√©brer avec une bonne dose de chocolat et de joie !"
  - "Wow, c'est incroyable ! Tu as d√©couvert un ≈ìuf cach√© √† la perfection. Tu pourrais peut-√™tre envisager de travailler pour la DGSE."
spotted:
  - "Oh l√† l√†, {user} a mis la main sur un ≈ìuf tr√®s convoit√© ! Mais attention, les autres joueurs ont l'air de flairer la bonne affaire !"
  - "Bien jou√©, {user} ! Mais ne te repose pas sur tes lauriers, car tes adversaires ont l'air de vouloir te piquer ton tr√©sor chocolat√© !"
  - "H√© h√©, {user} a trouv√© un ≈ìuf par hasard ! Mais il faut faire attention aux autres joueurs qui ont l'air de vouloir jouer les voleurs !"
  - "Ah, voil√† {user} qui a r√©ussi √† d√©nicher un ≈ìuf ! Mais il devrait faire attention, car les autres joueurs sont aux aguets et ont rep√©r√© sa trouvaille !"
  - "Bravo, {user} ! Mais il ne faudrait pas que tu te fasses voler ton ≈ìuf par les autres joueurs qui ont l'air de t'observer avec gourmandise !"
  - "Hourra ! {user} a trouv√© un ≈ìuf ! Mais maintenant, il doit faire face aux autres joueurs qui ont le regard aff√ªt√© et les doigts pr√™ts √† l'attraper. C'est le moment de sortir tes mouvements ninja pour garder ton pr√©cieux ≈ìuf !"
  - "Bien jou√©, {user} ! Tu as mis la main sur un ≈ìuf tant convoit√©. Mais n'oublie pas, les autres joueurs sont √† tes trousses et sont pr√™ts √† tout pour mettre la main dessus. Esquive, plonge et cours, et garde ton ≈ìuf en s√©curit√© !"
  - "F√©licitations, {user}, tu as remport√© la chasse √† l'≈ìuf ! Mais maintenant, les autres joueurs sont √† tes trousses et pr√™ts √† tout pour le r√©cup√©rer. Garde un ≈ìil sur tes arri√®res et montre-leur qui est {le} boss de la chasse aux ≈ìufs !"
  - "F√©licitations {user} ! Tu as trouv√© un ≈ìuf tant convoit√© ! Cependant, tu n'es pas seul dans ce jeu, et tes ennemis t'ont d√©j√† rep√©r√©. Attention, √ßa risque de devenir une chasse aux ≈ìufs plut√¥t agressive !"
  - "H√© {user}, Tu es un{e} vrai Sherlock Holmes ! Tu as r√©ussi √† trouver un ≈ìuf, mais tes adversaires ont flair√© le coup et ils sont en route pour le prendre ! Pr√©pare-toi √† d√©fendre ton butin de toutes tes forces !"
  - "Oh l√† l√†, {user} ! Tu as r√©ussi √† trouver un ≈ìuf ! C'est vraiment incroyable ! Malheureusement, tes adversaires sont tr√®s jaloux de ta r√©ussite, et ils vont tout faire pour te d√©pouiller. Sois sur tes gardes et va chercher ton tr√©sor !"
  - "Bravo {user} ! Tu as trouv√© un ≈ìuf ! Mais ne te repose pas sur tes lauriers, car les autres joueurs vont tout faire pour le voler ! Si tu veux le garder, il va falloir √™tre plus rapide, plus malin et plus rus√©{e} qu'eux !"
  - "Incroyable {user} ! Tu as trouv√© un ≈ìuf ! Mais attention, tes adversaires sont d√©j√† en train de te traquer ! Pr√©pare-toi √† une course-poursuite effr√©n√©e et amusante pour d√©fendre ton troph√©e ! Alors, es-tu pr√™t{e} √† relever le d√©fi ?"
appear:
  - "Le myst√®re de P√¢ques s'√©paissit, un ≈ìuf vient d'appara√Ætre sous vos yeux √©bahis !"
  - "Oh, regardez ! Un petit coquin d'≈ìuf s'est cach√© ici !"
  - "Levez les yeux et admirez ! Un ≈ìuf vient d'√™tre d√©couvert !"
  - "Alerte ! Alertez les chasseurs d'≈ìufs ! Un ≈ìuf vient de faire son apparition dans le coin !"
  - "On dirait que la chasse √† l'≈ìuf a commenc√©, un petit malin vient de se cacher ici !"
  - "Le soleil brille, les oiseaux chantent et les ≈ìufs apparaissent comme par magie !"
  - "La f√™te de P√¢ques ne serait pas compl√®te sans un peu de chasse aux ≈ìufs, et voil√† que l'un d'entre eux vient montrer le bout de son nez !"
  - "Les cloches de P√¢ques ont-elles sonn√© ? Non, c'est juste un ≈ìuf qui vient de faire une apparition surprise !"
  - "Regardez bien o√π vous mettez les pieds, un ≈ìuf farceur a d√©cid√© de se cacher ici !"
  - "Un ≈ìuf tout beau, tout frais, est apparu devant vous tel un cadeau tomb√© du ciel !"
  - "Soudain, un ≈ìuf color√© est sorti de sa cachette pour se montrer au grand jour."
  - "Vous avez cherch√© partout, mais finalement un ≈ìuf s'est laiss√© d√©couvrir avec plaisir."
  - "Comme par magie, un ≈ìuf est apparu juste sous vos nez, pr√™t √† √™tre chass√© !"
  - "Apr√®s une recherche intensive, un ≈ìuf a √©t√© d√©couvert dans son nid douillet."
  - "Les yeux √©merveill√©s, vous voyez un ≈ìuf √©clatant de couleurs se montrer timidement."
  - "Tout √† coup, un ≈ìuf est sorti de nulle part, comme si c'√©tait une √©vidence qu'il soit l√†."
  - "Les chasseurs ont presque abandonn√©, mais heureusement, un ≈ìuf est apparu pour leur redonner espoir."
  - "Alors que vous cherchiez encore et encore, un ≈ìuf a d√©cid√© de se montrer pour vous faciliter la t√¢che !"
action:
  - text: "Ramasser calmement l'≈ìuf"
    success:
      text: "Sa sagesse lui a permis d'arriver en vie jusqu'√† l'≈ìuf."
      gif: https://media.tenor.com/13sYDxqgJxkAAAAC/cute-fail.gif
    fail:
      text: "{Iel} s'est pr√©cipit√©{e} et n'a pas vu le danger !"
      gif: https://media.tenor.com/jRN1rDkw3RAAAAAC/tia-be-like-here-tilki-tula-hunter.gif
  - text: "Roulade pour attraper l'≈ìuf"
    success:
      text: "{Iel} effectue une roulade √† la perfection et s'empare de l'≈ìuf."
      gif: https://media.tenor.com/3jJ7jUrduLAAAAAC/raccoon-elden-ring.gif
    fail:
      text: "{Iel} se tape la t√™te contre un mur en essayant de faire une roulade."
      gif: https://media.tenor.com/sEH-VStJ0OEAAAAC/roll-cat.gif
  - text: "Canne √† p√™che pour voler l'≈ìuf"
    success:
      text: "Une canne √† p√™che ? √Ä la main c'est plus rapide !"
      gif: https://media.tenor.com/ByLaEQYy5y8AAAAC/fishing-caught.gif
    fail:
      text: "{Iel} fait des dommages collat√©raux."
      gif: https://media.tenor.com/R1k5xMnbQ9YAAAAC/fish-fishing.gif
  - text: "Courir jusqu'√† l'≈ìuf"
    success:
      text: "Tel Flash, {iel} s'empare de l'≈ìuf √† une vitesse ph√©nom√©nale !"
      gif: https://media.tenor.com/OOLXbK3qSn0AAAAC/flash-run.gif
    fail:
      text: "Sa rapidit√© lui a jou√© des tours."
      gif: https://i.makeagif.com/media/3-01-2017/q_GF_o.gif
  - text: "S√©curiser l'≈ìuf"
    success:
      text: "C'est un raid d'une efficacit√© incontestable, {iel} s'empare de l'≈ìuf."
      gif: https://media.tenor.com/1AhUNYnySx4AAAAC/f-bi-raid.gif
    fail:
      text: "{Iel} a oubli√© qu'il y avait aussi des ≈ìufs dans son panier !"
      gif: https://i.gifer.com/IQED.gif
  - text: "Voler l'≈ìuf"
    success:
      text: "{Iel} vole l'≈ìuf avec une discr√©tion qui lui est propre, donc aucune."
      gif: https://i.makeagif.com/media/5-13-2015/95FLVz.gif
    fail:
      text: "{Iel} rate son vol et perd un peu de sa dignit√© au passage."
      gif: https://media.tenor.com/FoRxXGhnH2EAAAAC/gun-fail.gif
  - text: "Mettre l'≈ìuf dans le panier"
    success:
      text: "C'est un magnifique panier qu'{iel} nous fait l√† !"
      gif: https://media.tenor.com/OI7r9b2aHawAAAAC/basketball-mj.gif
    fail:
      text: "Il semblerait que mettre un ≈ìuf dans un panier serait trop dur pour certain."
      gif: https://media.tenor.com/LbVdHqEDChYAAAAC/ralph-easter-egg.gif
  - text: "Construire une machine √† ≈ìufs"
    success:
      text: "C'est une incroyable machine qu'{iel} a fait, malheureusement cela n'a permis de r√©cup√©rer qu'un ≈ìuf."
      gif: https://media.tenor.com/w5KbvzaYbSMAAAAC/satisfactory.gif
    fail:
      text: "Choqu√©{e} par la machine √† ≈ìuf, {iel} reste t√©tanis√©{e} et laisse son ≈ìuf partir."
      gif: https://i.gifer.com/Wdts.gif
  - text: "Payer pour l'≈ìuf"
    success:
      text: "{Iel} r√©ussi √† corrompre le lapin de P√¢que pour qu'il lui laisse l'≈ìuf."
      gif: https://media.tenor.com/BT6bMyOIbawAAAAC/cop-corruption.gif
    fail:
      text: "{Iel} a oubli√© qu'{iel} √©tait pauvre."
      gif: https://media.tenor.com/rdvWdzGheQYAAAAd/drama-queen-wallet.gif
  - text: "Se battre pour l'≈ìuf"
    success:
      text: "La violence ne r√©sout rien, {iel} s'empare de l'≈ìuf avec douceur üíû"
      gif: https://media.tenor.com/pHwzmlVwEocAAAAd/heejake.gif
    fail:
      text: "{Iel} √©tait trop concentr√©{e} sur le combat. {Iel} a laiss√© passer l'≈ìuf."
      gif: https://media.tenor.com/l5sIE_3H3EEAAAAd/cats-fighting-fighting-cats.gif
  - text: "Danser pour l'≈ìuf"
    success:
      text: "{Iel} effectue une danse endiabl√©e. Tous les yeux sont riv√©s sur {lui}, {iel} s'empare de l'≈ìuf avec l'admiration de tous."
      gif: https://media.tenor.com/NDIx856G0XIAAAAC/dance-turkey.gif
    fail:
      text: "Personne n'aurait aim√© √™tre √† sa place. {Iel} se casse la gueule avec honte."
      gif: https://media.tenor.com/nMcbTp1sQgYAAAAC/dance-oops.gif
  - text: "Regarder intensivement l'≈ìuf"
    success:
      text: "Son regard remplit de jugement et de puissance pousse les autres chasseurs √† lui laisser l'≈ìuf."
      gif: https://media.tenor.com/OVUDwIM8mBkAAAAC/cat-cat-stare.gif
    fail:
      text: "{Iel} se fait surprendre par l'≈ìuf."
      gif: https://media.tenor.com/Dui2bqe8O0gAAAAC/children-demolition.gif
  - text: "Assommer le lapin de P√¢ques"
    success:
      text: "{Iel} porte un coup assommant au lapin de P√¢ques, c'est un coup critique ! {Iel} obtient un ≈ìuf."
      gif: https://media.tenor.com/Aofnhf0GL6AAAAAd/happy-easter.gif
    fail:
      text: "Le lapin de P√¢ques n'a pas trop l'air d'aimer sa tentative d'assassinat. Il lui d√©fonce violemment sa race."
      gif: https://media.tenor.com/Zv4FWUoX2xoAAAAC/happy-easter.gif
